### PR TITLE
Include tailwind as a dependency to ship with styles

### PR DESCRIPTION
**Pull request by duranmla**
**What:**
In order to try to ship with styles and avoid recurrent issues with them add tailwindcss as part of the bundle

**Note**
_This is actually an hypothesis, I am not sure if this will work_

### CODE REVIEW

**Comment by orlando** [comment]
@duranmla mmm is this the way to integrate it? I thought we would generate a `union-component.css` file we can include via import. I'm not 100% positive on what's the right way to do this

**Comment by duranmla** [comment]
Then we need to generate the file. This is a naive intent as we don't do anything currently @orlando but your comment sounds reasonable. I though tho that if we add as a dependency then the bundle will include the generated CSS from the styled components that has `tw`

**Comment by orlando** [comment]
@duranmla what can we check to make sure we are not affecting bundle size or performance? I guess we can check bundlephobia to see if tailwind is affecting in some way?

**Comment by duranmla** [comment]
I think it is going to be affected of course as we will ship with more things. But let's do the following:
_Let's associate this PR to a ticket and look for the "right" way to ship components with tailwindcss_

**Comment by duranmla** [comment]
We will get back to this topic [when this one](https://app.asana.com/0/1195530778765030/1200264032603328)

**Pull request closed without merging**
